// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reestrs.Database;

#nullable disable

namespace Reestrs.Migrations
{
    [DbContext(typeof(ReestrsDbContext))]
    [Migration("20231221045642_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reestrs.Database.Models.B_DIAG", b =>
                {
                    b.Property<int>("B_DIAGId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("B_DIAGId"));

                    b.Property<int>("DIAG_CODE")
                        .HasColumnType("int");

                    b.Property<DateTime>("DIAG_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DIAG_RSLT")
                        .HasColumnType("int");

                    b.Property<int>("DIAG_TIP")
                        .HasColumnType("int");

                    b.Property<int?>("ONK_SLId")
                        .HasColumnType("int");

                    b.Property<int?>("REC_RSLT")
                        .HasColumnType("int");

                    b.HasKey("B_DIAGId");

                    b.HasIndex("ONK_SLId");

                    b.ToTable("B_DIAGs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.B_PROT", b =>
                {
                    b.Property<int>("B_PROTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("B_PROTId"));

                    b.Property<DateTime>("D_PROT")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ONK_SLId")
                        .HasColumnType("int");

                    b.Property<int>("PROT")
                        .HasColumnType("int");

                    b.HasKey("B_PROTId");

                    b.HasIndex("ONK_SLId");

                    b.ToTable("B_PROTs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.CONS", b =>
                {
                    b.Property<int>("CONSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CONSId"));

                    b.Property<DateTime>("DT_CONS")
                        .HasColumnType("datetime2");

                    b.Property<int>("PR_CONS")
                        .HasColumnType("int");

                    b.Property<int?>("SLId")
                        .HasColumnType("int");

                    b.HasKey("CONSId");

                    b.HasIndex("SLId");

                    b.ToTable("CONSs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.DS2_N", b =>
                {
                    b.Property<int>("DS2_NId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DS2_NId"));

                    b.Property<string>("DS2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DS2_PR")
                        .HasColumnType("int");

                    b.Property<int>("PR_DS2_N")
                        .HasColumnType("int");

                    b.Property<int?>("SLId")
                        .HasColumnType("int");

                    b.HasKey("DS2_NId");

                    b.HasIndex("SLId");

                    b.ToTable("DS2_Ns");
                });

            modelBuilder.Entity("Reestrs.Database.Models.KSG_KPG", b =>
                {
                    b.Property<int>("KSG_KPGId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KSG_KPGId"));

                    b.Property<decimal>("BZTSZ")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("CRIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IT_SL")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal(6,5)");

                    b.Property<decimal>("KOEF_D")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal(7,5)");

                    b.Property<decimal>("KOEF_U")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal(7,5)");

                    b.Property<decimal>("KOEF_UP")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal(7,5)");

                    b.Property<decimal>("KOEF_Z")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal(8,5)");

                    b.Property<int>("KSG_PG")
                        .HasColumnType("int");

                    b.Property<string>("N_KPG")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("N_KSG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SL_K")
                        .HasColumnType("int");

                    b.Property<int>("VER_KSG")
                        .HasColumnType("int");

                    b.HasKey("KSG_KPGId");

                    b.ToTable("KSG_KPGs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.LEK_DOSE", b =>
                {
                    b.Property<int>("LEK_DOSEId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LEK_DOSEId"));

                    b.Property<int>("COL_INJ")
                        .HasColumnType("int");

                    b.Property<decimal>("DOSE_INJ")
                        .HasPrecision(14, 7)
                        .HasColumnType("decimal(14,7)");

                    b.Property<string>("ED_IZM")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("METHOD_INJ")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("LEK_DOSEId");

                    b.ToTable("LEK_DOSEs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.LEK_PR", b =>
                {
                    b.Property<int>("LEK_PRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LEK_PRId"));

                    b.Property<string>("CODE_SH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("COD_MARK")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DATA_INJ")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LEK_DOSEId")
                        .HasColumnType("int");

                    b.Property<int?>("ONK_USLId")
                        .HasColumnType("int");

                    b.Property<string>("REGNUM")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("SLId")
                        .HasColumnType("int");

                    b.HasKey("LEK_PRId");

                    b.HasIndex("LEK_DOSEId");

                    b.HasIndex("ONK_USLId");

                    b.HasIndex("SLId");

                    b.ToTable("LEK_PRs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.MED_DEV", b =>
                {
                    b.Property<int>("MED_DEVId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MED_DEVId"));

                    b.Property<int>("CODE_MEDDEV")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATE_MED")
                        .HasColumnType("datetime2");

                    b.Property<string>("NUMBER_SER")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("USLId")
                        .HasColumnType("int");

                    b.HasKey("MED_DEVId");

                    b.HasIndex("USLId");

                    b.ToTable("MED_DEVs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.MR_USL_N", b =>
                {
                    b.Property<int>("MR_USL_NId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MR_USL_NId"));

                    b.Property<string>("CODE_MD")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("MR_N")
                        .HasColumnType("int");

                    b.Property<int?>("PRVS")
                        .HasColumnType("int");

                    b.Property<int?>("USLId")
                        .HasColumnType("int");

                    b.HasKey("MR_USL_NId");

                    b.HasIndex("USLId");

                    b.ToTable("MR_USL_Ns");
                });

            modelBuilder.Entity("Reestrs.Database.Models.NAPR", b =>
                {
                    b.Property<int>("NAPRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NAPRId"));

                    b.Property<int?>("MET_ISSL")
                        .HasColumnType("int");

                    b.Property<DateTime>("NAPR_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAPR_MO")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("NAPR_USL")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("NAPR_V")
                        .HasColumnType("int");

                    b.Property<int?>("SLId")
                        .HasColumnType("int");

                    b.HasKey("NAPRId");

                    b.HasIndex("SLId");

                    b.ToTable("NAPRs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.NAZ", b =>
                {
                    b.Property<int>("NAZId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NAZId"));

                    b.Property<DateTime?>("NAPR_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAPR_MO")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("NAZ_N")
                        .HasColumnType("int");

                    b.Property<int?>("NAZ_PK")
                        .HasColumnType("int");

                    b.Property<int?>("NAZ_PMP")
                        .HasColumnType("int");

                    b.Property<int>("NAZ_R")
                        .HasColumnType("int");

                    b.Property<int?>("NAZ_SP")
                        .HasColumnType("int");

                    b.Property<string>("NAZ_USL")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("NAZ_V")
                        .HasColumnType("int");

                    b.Property<int?>("SLId")
                        .HasColumnType("int");

                    b.HasKey("NAZId");

                    b.HasIndex("SLId");

                    b.ToTable("NAZs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ONK_SL", b =>
                {
                    b.Property<int>("ONK_SLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ONK_SLId"));

                    b.Property<decimal>("BSA")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("DS1_T")
                        .HasColumnType("int");

                    b.Property<int?>("HEI")
                        .HasColumnType("int");

                    b.Property<int?>("K_FR")
                        .HasColumnType("int");

                    b.Property<int?>("MTSTZ")
                        .HasColumnType("int");

                    b.Property<int?>("ONK_M")
                        .HasColumnType("int");

                    b.Property<int?>("ONK_N")
                        .HasColumnType("int");

                    b.Property<int?>("ONK_T")
                        .HasColumnType("int");

                    b.Property<decimal>("SOD")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("STAD")
                        .HasColumnType("int");

                    b.Property<decimal?>("WEI")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("ONK_SLId");

                    b.ToTable("ONK_SLs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ONK_USL", b =>
                {
                    b.Property<int>("ONK_USLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ONK_USLId"));

                    b.Property<int?>("HIR_TIP")
                        .HasColumnType("int");

                    b.Property<int?>("LEK_TIP_L")
                        .HasColumnType("int");

                    b.Property<int?>("LEK_TIP_V")
                        .HasColumnType("int");

                    b.Property<int?>("LUCH_TIP")
                        .HasColumnType("int");

                    b.Property<int?>("ONK_SLId")
                        .HasColumnType("int");

                    b.Property<int?>("PPTR")
                        .HasColumnType("int");

                    b.Property<int>("USL_TIP")
                        .HasColumnType("int");

                    b.HasKey("ONK_USLId");

                    b.HasIndex("ONK_SLId");

                    b.ToTable("ONK_USLs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.PACIENT", b =>
                {
                    b.Property<int>("PACIENTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PACIENTId"));

                    b.Property<string>("COMENTP")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DOCDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOCNUM")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DOCORG")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DOCSER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DOCTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DOST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOST_P")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DR_P")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENP")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("FAM")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FAM_P")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ID_PAC")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IM")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("IM_P")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("INV")
                        .HasColumnType("int");

                    b.Property<string>("MR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MSE")
                        .HasColumnType("int");

                    b.Property<string>("NOVOR")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("NPOLIS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OKATOG")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("OKATOP")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("OT")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OT_P")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SMO")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SMO_NAM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SMO_OGRN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SMO_OK")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SNILS")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("SPOLIS")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ST_OKATO")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("VNOV_D")
                        .HasColumnType("int");

                    b.Property<int?>("VPOLIS")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("W")
                        .HasColumnType("int");

                    b.Property<int?>("W_P")
                        .HasColumnType("int");

                    b.HasKey("PACIENTId");

                    b.ToTable("PACIENTs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.Pers", b =>
                {
                    b.Property<int>("PersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersId"));

                    b.Property<string>("COMENTP")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DOCDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOCNUM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DOCORG")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DOCSER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DOCTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("DOST")
                        .HasColumnType("int");

                    b.Property<int?>("DOST_P")
                        .HasColumnType("int");

                    b.Property<DateTime>("DR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DR_P")
                        .HasColumnType("datetime2");

                    b.Property<string>("FAM")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FAM_P")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ID_PAC")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IM")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("IM_P")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OKATOG")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("OKATOP")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("OT")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OT_P")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PersListId")
                        .HasColumnType("int");

                    b.Property<string>("SNILS")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("TEL")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("W")
                        .HasColumnType("int");

                    b.Property<int?>("W_P")
                        .HasColumnType("int");

                    b.HasKey("PersId");

                    b.HasIndex("PersListId");

                    b.ToTable("Pers");
                });

            modelBuilder.Entity("Reestrs.Database.Models.PersList", b =>
                {
                    b.Property<int>("PersListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersListId"));

                    b.HasKey("PersListId");

                    b.ToTable("PersLists");
                });

            modelBuilder.Entity("Reestrs.Database.Models.SANK", b =>
                {
                    b.Property<int>("SankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SankId"));

                    b.Property<string>("CODE_EXP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DATE_ACT")
                        .HasColumnType("datetime2");

                    b.Property<string>("NUM_ACT")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PersListId")
                        .HasColumnType("int");

                    b.Property<string>("SL_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_CODE")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("S_COM")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("S_IST")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("S_OSN")
                        .HasColumnType("int");

                    b.Property<decimal>("S_SUM")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<string>("S_TIP")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("Z_SLId")
                        .HasColumnType("int");

                    b.HasKey("SankId");

                    b.HasIndex("PersListId")
                        .IsUnique();

                    b.HasIndex("Z_SLId");

                    b.ToTable("SANKs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.SCHET", b =>
                {
                    b.Property<int>("SCHETId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SCHETId"));

                    b.Property<int>("CODE")
                        .HasColumnType("int");

                    b.Property<string>("CODE_MO")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("COMENTS")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DISP")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("DSCHET")
                        .HasColumnType("datetime2");

                    b.Property<int>("MONTH")
                        .HasColumnType("int");

                    b.Property<string>("NSCHET")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PLAT")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal?>("SANK_EKMP")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<decimal?>("SANK_MEE")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<decimal?>("SANK_MEK")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<decimal?>("SUMMAP")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<decimal>("SUMMAV")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<int>("YEAR")
                        .HasColumnType("int");

                    b.HasKey("SCHETId");

                    b.ToTable("SCHETs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.SL", b =>
                {
                    b.Property<int>("SLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLId"));

                    b.Property<string>("CODE_MES1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE_MES2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("COMENTSL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("C_ZAB")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATE_1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DATE_2")
                        .HasColumnType("datetime2");

                    b.Property<int>("DET")
                        .HasColumnType("int");

                    b.Property<int?>("DISP")
                        .HasColumnType("int");

                    b.Property<int?>("DN")
                        .HasColumnType("int");

                    b.Property<string>("DS0")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DS1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DS1_PR")
                        .HasColumnType("int");

                    b.Property<string>("DS2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DS3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DS_ONK")
                        .HasColumnType("int");

                    b.Property<decimal?>("ED_COL")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("IDDOKT")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("KD")
                        .HasColumnType("int");

                    b.Property<int?>("KSG_KPGId")
                        .HasColumnType("int");

                    b.Property<string>("LPU_1")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("METOD_HMP")
                        .HasColumnType("int");

                    b.Property<string>("NHISTORY")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ONK_SLId")
                        .HasColumnType("int");

                    b.Property<int?>("PODR")
                        .HasColumnType("int");

                    b.Property<int>("PROFIL")
                        .HasColumnType("int");

                    b.Property<int?>("PROFIL_K")
                        .HasColumnType("int");

                    b.Property<int>("PRVS")
                        .HasColumnType("int");

                    b.Property<int?>("PR_D_N")
                        .HasColumnType("int");

                    b.Property<string>("P_CEL")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("P_PER")
                        .HasColumnType("int");

                    b.Property<int?>("REAB")
                        .HasColumnType("int");

                    b.Property<string>("SL_ID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("SUM_M")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<DateTime?>("TAL_D")
                        .HasColumnType("datetime2");

                    b.Property<string>("TAL_NUM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TAL_P")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TARIF")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<string>("VERS_SPEC")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("VID_HMP")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("WEI")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<int?>("Z_SLId")
                        .HasColumnType("int");

                    b.HasKey("SLId");

                    b.HasIndex("KSG_KPGId");

                    b.HasIndex("ONK_SLId");

                    b.HasIndex("Z_SLId");

                    b.ToTable("SLs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.SL_KOEF", b =>
                {
                    b.Property<int>("SL_KOEFId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SL_KOEFId"));

                    b.Property<int>("IDSL")
                        .HasColumnType("int");

                    b.Property<int?>("KSG_KPGId")
                        .HasColumnType("int");

                    b.Property<decimal>("Z_SL")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal(6,5)");

                    b.HasKey("SL_KOEFId");

                    b.HasIndex("KSG_KPGId");

                    b.ToTable("SL_KOEFs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.USL", b =>
                {
                    b.Property<int>("USLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USLId"));

                    b.Property<string>("CODE_MD")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CODE_USL")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("COMENTU")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<DateTime>("DATE_IN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DATE_OUT")
                        .HasColumnType("datetime2");

                    b.Property<int>("DET")
                        .HasColumnType("int");

                    b.Property<string>("DS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IDSERV")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("KOL_USL")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("LPU")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("LPU_1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("NPL")
                        .HasColumnType("int");

                    b.Property<int?>("PODR")
                        .HasColumnType("int");

                    b.Property<int?>("PROFIL")
                        .HasColumnType("int");

                    b.Property<int?>("PRVS")
                        .HasColumnType("int");

                    b.Property<int>("P_OTK")
                        .HasColumnType("int");

                    b.Property<int?>("SLId")
                        .HasColumnType("int");

                    b.Property<decimal>("SUMV_USL")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<decimal?>("TARIF")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<string>("VID_VME")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("USLId");

                    b.HasIndex("SLId");

                    b.ToTable("USLs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZAP", b =>
                {
                    b.Property<int>("ZAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZAPId"));

                    b.Property<int>("PACIENTId")
                        .HasColumnType("int");

                    b.Property<int?>("ZL_LISTId")
                        .HasColumnType("int");

                    b.Property<int>("Z_SLId")
                        .HasColumnType("int");

                    b.HasKey("ZAPId");

                    b.HasIndex("PACIENTId");

                    b.HasIndex("ZL_LISTId");

                    b.HasIndex("Z_SLId");

                    b.ToTable("ZAPs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZGLV_H", b =>
                {
                    b.Property<int>("ZGLVId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZGLVId"));

                    b.Property<string>("C_OKATO1")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DATA")
                        .HasColumnType("datetime2");

                    b.Property<string>("FILENAME")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("OKATO_OMS")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SD_Z")
                        .HasColumnType("int");

                    b.Property<string>("VERSION")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ZGLVId");

                    b.ToTable("Zglvs_h");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZGLV_L", b =>
                {
                    b.Property<int>("ZglvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZglvId"));

                    b.Property<DateTime>("DATA")
                        .HasColumnType("datetime2");

                    b.Property<string>("FILENAME")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("FILENAME1")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<int>("PersListId")
                        .HasColumnType("int");

                    b.Property<string>("VERSION")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ZglvId");

                    b.HasIndex("PersListId")
                        .IsUnique();

                    b.ToTable("Zglvs_l");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZL_LIST", b =>
                {
                    b.Property<int>("ZL_LISTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZL_LISTId"));

                    b.Property<int>("SCHETId")
                        .HasColumnType("int");

                    b.Property<int>("ZGLVId")
                        .HasColumnType("int");

                    b.HasKey("ZL_LISTId");

                    b.HasIndex("SCHETId");

                    b.HasIndex("ZGLVId");

                    b.ToTable("ZL_LISTs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.Z_SL", b =>
                {
                    b.Property<int>("Z_SLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Z_SLId"));

                    b.Property<DateTime>("DATE_Z_1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DATE_Z_2")
                        .HasColumnType("datetime2");

                    b.Property<int>("FOR_POM")
                        .HasColumnType("int");

                    b.Property<int>("IDCASE")
                        .HasColumnType("int");

                    b.Property<int>("IDSP")
                        .HasColumnType("int");

                    b.Property<int>("ISHOD")
                        .HasColumnType("int");

                    b.Property<int?>("KD_Z")
                        .HasColumnType("int");

                    b.Property<string>("LPU")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("NPR_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("NPR_MO")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("OPLATA")
                        .HasColumnType("int");

                    b.Property<int?>("OS_SLUCH")
                        .HasColumnType("int");

                    b.Property<int?>("P_DISP2")
                        .HasColumnType("int");

                    b.Property<int>("P_OTK")
                        .HasColumnType("int");

                    b.Property<int>("RSLT")
                        .HasColumnType("int");

                    b.Property<int?>("RSLT_D")
                        .HasColumnType("int");

                    b.Property<decimal?>("SUMP")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<decimal>("SUMV")
                        .HasPrecision(17, 2)
                        .HasColumnType("decimal(17,2)");

                    b.Property<int>("USL_OK")
                        .HasColumnType("int");

                    b.Property<int>("VBR")
                        .HasColumnType("int");

                    b.Property<int?>("VB_P")
                        .HasColumnType("int");

                    b.Property<int>("VIDPOM")
                        .HasColumnType("int");

                    b.Property<int?>("VNOV_M")
                        .HasColumnType("int");

                    b.HasKey("Z_SLId");

                    b.ToTable("Z_SLs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.B_DIAG", b =>
                {
                    b.HasOne("Reestrs.Database.Models.ONK_SL", null)
                        .WithMany("B_DIAG")
                        .HasForeignKey("ONK_SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.B_PROT", b =>
                {
                    b.HasOne("Reestrs.Database.Models.ONK_SL", null)
                        .WithMany("B_PROT")
                        .HasForeignKey("ONK_SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.CONS", b =>
                {
                    b.HasOne("Reestrs.Database.Models.SL", null)
                        .WithMany("CONSs")
                        .HasForeignKey("SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.DS2_N", b =>
                {
                    b.HasOne("Reestrs.Database.Models.SL", null)
                        .WithMany("DS2_N")
                        .HasForeignKey("SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.LEK_PR", b =>
                {
                    b.HasOne("Reestrs.Database.Models.LEK_DOSE", "LEK_DOSE")
                        .WithMany()
                        .HasForeignKey("LEK_DOSEId");

                    b.HasOne("Reestrs.Database.Models.ONK_USL", null)
                        .WithMany("LEK_PR")
                        .HasForeignKey("ONK_USLId");

                    b.HasOne("Reestrs.Database.Models.SL", null)
                        .WithMany("LEK_PRs")
                        .HasForeignKey("SLId");

                    b.Navigation("LEK_DOSE");
                });

            modelBuilder.Entity("Reestrs.Database.Models.MED_DEV", b =>
                {
                    b.HasOne("Reestrs.Database.Models.USL", null)
                        .WithMany("MED_DEV")
                        .HasForeignKey("USLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.MR_USL_N", b =>
                {
                    b.HasOne("Reestrs.Database.Models.USL", null)
                        .WithMany("MR_USL_N")
                        .HasForeignKey("USLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.NAPR", b =>
                {
                    b.HasOne("Reestrs.Database.Models.SL", null)
                        .WithMany("NAPRs")
                        .HasForeignKey("SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.NAZ", b =>
                {
                    b.HasOne("Reestrs.Database.Models.SL", null)
                        .WithMany("NAZs")
                        .HasForeignKey("SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ONK_USL", b =>
                {
                    b.HasOne("Reestrs.Database.Models.ONK_SL", null)
                        .WithMany("ONK_USL")
                        .HasForeignKey("ONK_SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.Pers", b =>
                {
                    b.HasOne("Reestrs.Database.Models.PersList", "PersList")
                        .WithMany("PERS")
                        .HasForeignKey("PersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersList");
                });

            modelBuilder.Entity("Reestrs.Database.Models.SANK", b =>
                {
                    b.HasOne("Reestrs.Database.Models.PersList", "PersList")
                        .WithOne("SANK")
                        .HasForeignKey("Reestrs.Database.Models.SANK", "PersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reestrs.Database.Models.Z_SL", null)
                        .WithMany("SANKs")
                        .HasForeignKey("Z_SLId");

                    b.Navigation("PersList");
                });

            modelBuilder.Entity("Reestrs.Database.Models.SL", b =>
                {
                    b.HasOne("Reestrs.Database.Models.KSG_KPG", "KSG_KPG")
                        .WithMany()
                        .HasForeignKey("KSG_KPGId");

                    b.HasOne("Reestrs.Database.Models.ONK_SL", "ONK_SL")
                        .WithMany()
                        .HasForeignKey("ONK_SLId");

                    b.HasOne("Reestrs.Database.Models.Z_SL", null)
                        .WithMany("SLs")
                        .HasForeignKey("Z_SLId");

                    b.Navigation("KSG_KPG");

                    b.Navigation("ONK_SL");
                });

            modelBuilder.Entity("Reestrs.Database.Models.SL_KOEF", b =>
                {
                    b.HasOne("Reestrs.Database.Models.KSG_KPG", null)
                        .WithMany("SL_KOEF")
                        .HasForeignKey("KSG_KPGId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.USL", b =>
                {
                    b.HasOne("Reestrs.Database.Models.SL", null)
                        .WithMany("USLs")
                        .HasForeignKey("SLId");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZAP", b =>
                {
                    b.HasOne("Reestrs.Database.Models.PACIENT", "PACIENT")
                        .WithMany()
                        .HasForeignKey("PACIENTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reestrs.Database.Models.ZL_LIST", null)
                        .WithMany("ZAPs")
                        .HasForeignKey("ZL_LISTId");

                    b.HasOne("Reestrs.Database.Models.Z_SL", "Z_SL")
                        .WithMany()
                        .HasForeignKey("Z_SLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PACIENT");

                    b.Navigation("Z_SL");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZGLV_L", b =>
                {
                    b.HasOne("Reestrs.Database.Models.PersList", "PersList")
                        .WithOne("ZGLV")
                        .HasForeignKey("Reestrs.Database.Models.ZGLV_L", "PersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersList");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZL_LIST", b =>
                {
                    b.HasOne("Reestrs.Database.Models.SCHET", "SCHET")
                        .WithMany()
                        .HasForeignKey("SCHETId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reestrs.Database.Models.ZGLV_H", "ZGLV")
                        .WithMany()
                        .HasForeignKey("ZGLVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SCHET");

                    b.Navigation("ZGLV");
                });

            modelBuilder.Entity("Reestrs.Database.Models.KSG_KPG", b =>
                {
                    b.Navigation("SL_KOEF");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ONK_SL", b =>
                {
                    b.Navigation("B_DIAG");

                    b.Navigation("B_PROT");

                    b.Navigation("ONK_USL");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ONK_USL", b =>
                {
                    b.Navigation("LEK_PR");
                });

            modelBuilder.Entity("Reestrs.Database.Models.PersList", b =>
                {
                    b.Navigation("PERS");

                    b.Navigation("SANK")
                        .IsRequired();

                    b.Navigation("ZGLV")
                        .IsRequired();
                });

            modelBuilder.Entity("Reestrs.Database.Models.SL", b =>
                {
                    b.Navigation("CONSs");

                    b.Navigation("DS2_N");

                    b.Navigation("LEK_PRs");

                    b.Navigation("NAPRs");

                    b.Navigation("NAZs");

                    b.Navigation("USLs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.USL", b =>
                {
                    b.Navigation("MED_DEV");

                    b.Navigation("MR_USL_N");
                });

            modelBuilder.Entity("Reestrs.Database.Models.ZL_LIST", b =>
                {
                    b.Navigation("ZAPs");
                });

            modelBuilder.Entity("Reestrs.Database.Models.Z_SL", b =>
                {
                    b.Navigation("SANKs");

                    b.Navigation("SLs");
                });
#pragma warning restore 612, 618
        }
    }
}
